ALTER TABLE LANGUAGE ADD COLUMN NAME VARCHAR(50);

UPDATE LANGUAGE SET NAME = 'English' WHERE CODE = 'en';
UPDATE LANGUAGE SET NAME = 'Español' WHERE CODE = 'es';
UPDATE LANGUAGE SET NAME = 'Català' WHERE CODE = 'ca';
UPDATE LANGUAGE SET NAME = 'Euskara' WHERE CODE = 'eu';
UPDATE LANGUAGE SET NAME = '日本語' WHERE CODE = 'jp';

ALTER TABLE LANGUAGE ALTER COLUMN NAME SET NOT NULL;